### ISSUE TITLE
[Major Bug] LiveSplit throwing exception after each new game

### ISSUE THREAD

**Issue by Master-64** [Master-64/Shrek2-LiveSplit#2]
Doesn't seem to occur for everyone. Error does not cause a crash for LiveSplit and application can be continued as normal. Only occurs with automatic timer start.

Error:
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: "System.Dynamic.ExpandoObject" does not contain a definition for "doneMaps"
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at CompiledScript.<>c__DisplayClass16.<Execute>b__14(Object s, EventArgs e) at c:\Users\EXAMPLE\AppData\Local\Temp\avdpg4ww.0.cs:line 82
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at LiveSplit.Model.TimerModel.Start()
   at Shrek2_LiveSplit.Data.Shrek2Component.OnNewGame()

**Comment by Master-64** [comment]
Caused by unknown .asl file in the user's directory. Closing issue as this isn't related to this project.
